AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CPS-COVID-ETL

  SAM Template for CSV_Update
Globals:
  Function:
    Timeout: 300

Resources:
  CPSCovidUpdateFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: csv_update/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 1024
      Policies:
        - S3FullAccessPolicy:
            BucketName: "cpscovid.com"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt UpdateTopic.TopicName
        - Statement:
          - Sid: AllowCacheInvalidation
            Effect: Allow
            Action:
            - cloudfront:CreateInvalidation
            Resource: "*"
      Events:
        # WeekDayStartUpdate:
        #   Type: Schedule
        #   Properties:
        #     Description: Activates CPS COVID Update Lambda Function every minute on 6am to 8pm weekdays.
        #     Enabled: True
        #     Schedule: "cron(* 11-23 ? * 2-6 *)" #every min on wed. neet to account for utc. 
        # WeekDayEndUpdate:
        #   Type: Schedule
        #   Properties:
        #     Description: Activates CPS COVID Update Lambda Function every minute on 6am to 8pm weekdays.
        #     Enabled: True
        #     Schedule: "cron(* 0 ? * 3-7 *)" #every min on wed. neet to account for utc.
        # WeekNightStartUpdate:
        #   Type: Schedule
        #   Properties:
        #     Description: Activates CPS COVID Update Lambda Function every 10 min on weeknights.
        #     Enabled: True
        #     Schedule: "cron(0/10 5-10 ? * 2-6 *)" #every 10 min on non-wed weekday.
        # WeekNightEndUpdate:
        #   Type: Schedule
        #   Properties:
        #     Description: Activates CPS COVID Update Lambda Function every 10 min on weeknights.
        #     Enabled: True
        #     Schedule: "cron(0/10 1-4 ? * 3-7 *)" #every 10 min on non-wed weekday.
        # WeekendStartUpdate:
        #   Type: Schedule
        #   Properties:
        #     Description: Activates CPS COVID Update Lambda Function every hour on Weekends.
        #     Enabled: True
        #     Schedule: "cron(0 5-23 ? * 1,7 *)" #every hour on sun/sat. 
        testUpdate:
          Type: Schedule
          Properties:
            Description: Activates CPS COVID Update Lambda Function every hour
            Enabled: True
            Schedule: "cron(0 * ? * * *)" #every hour every day
        # WeekendEndUpdate:
        #   Type: Schedule
        #   Properties:
        #     Description: Activates CPS COVID Update Lambda Function every hour on Weekends.
        #     Enabled: True
        #     Schedule: "cron(0 1-4 ? * 1,2 *)" #every hour on sun/sat. 
      Environment:
        Variables:
          snsTopicArn: !Ref UpdateTopic
          cloudfrontCache: "E28928I27HS5YI"
          consumer_key: ${CONSUMER_KEY}
          consumer_secret: ${CONSUMER_SECRET}
          access_token: ${ACCESS_TOKEN}
          access_token_secret: ${ACCESS_TOKEN_SECRET}
            
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: ondrey@gmail.com

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CPSCovidUpdateFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      TreatMissingData: notBreaching
      Statistic: Sum
      Threshold: '1'

  UpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: CPS numbers updated
      Subscription:
      - Protocol: email
        Endpoint: ondrey@gmail.com
  UpdateApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors: 
        AllowMethods: "'GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        # AllowCredentials: True
      StageName: Prod

  UpdateSubscriptionFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: subscribe/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Events:
        SubscribeAPI:
          Type: Api
          Properties: 
            Path: /prod
            Method: GET
            RestApiId: !Ref UpdateApi
      Policies:
        - SNSCrudPolicy:
            TopicName: !GetAtt UpdateTopic.TopicName
      Environment:
        Variables:
          snsTopicArn: !Ref UpdateTopic
        
Outputs:
  CPSCovidUpdateFunction:
    Description: "CPS COVID Update Lambda Function ARN"
    Value: !GetAtt CPSCovidUpdateFunction.Arn
  CPSCovidUpdateFunctionIamRole:
    Description: "Implicit IAM Role created for CPS COVID Update function"
    Value: !GetAtt CPSCovidUpdateFunctionRole.Arn 
  UpdateTopicARN:
    Description: "Topic created for sending updates"
    Value: !Ref UpdateTopic
  SubscribeAPI:
    Description: "API Gateway endpoint URL for Visitor Count function"
    # Value: !Ref UpdateApi
    Value: !Sub "https://${UpdateApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/prod/"
  
