AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CPS-COVID-ETL

  SAM Template for CSV_Update
Globals:
  Function:
    Timeout: 300

Resources:
  CPSCovidUpdateFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: csv_update/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 1024
      Policies:
        - S3FullAccessPolicy:
            BucketName: "cpscovid.com/*"
      Events:
        MidnightUpdate:
          Type: Schedule
          Properties:
            Description: Activates CPS COVID Update Lambda Function at the beginning of every hour.
            Enabled: True
            Schedule: "cron(0 * * * ? *)"
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint: ondrey@gmail.com

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CPSCovidUpdateFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      TreatMissingData: notBreaching
      Statistic: Sum
      Threshold: '1'

        
Outputs:
  CPSCovidUpdateFunction:
    Description: "CPS COVID Update Lambda Function ARN"
    Value: !GetAtt CPSCovidUpdateFunction.Arn
  CPSCovidUpdateFunctionIamRole:
    Description: "Implicit IAM Role created for CPS COVID Update function"
    Value: !GetAtt CPSCovidUpdateFunctionRole.Arn
